openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /v1/enrich:
    post:
      summary: Enrich
      operationId: enrich_v1_enrich_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MappingRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MappingResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    MapEntry:
      properties:
        mappedIdType:
          type: string
          title: Mappedidtype
        mappedIdValue:
          anyOf:
          - type: string
          - type: 'null'
          title: Mappedidvalue
        sources:
          items:
            type: string
            maxLength: 2083
            minLength: 1
            format: uri
          type: array
          title: Sources
        error:
          anyOf:
          - type: string
          - type: 'null'
          title: Error
      type: object
      required:
      - mappedIdType
      - sources
      title: MapEntry
    MappingRequest:
      properties:
        idType:
          type: string
          enum:
          - CUSIP
          - ISIN
          - FIGI
          - FIGI_COMPOSITE
          - FIGI_SHARE_CLASS
          title: Idtype
        idValue:
          type: string
          title: Idvalue
      type: object
      required:
      - idType
      - idValue
      title: MappingRequest
      description: Request payload for a single identifier.
    MappingResponse:
      properties:
        results:
          items:
            $ref: '#/components/schemas/MapEntry'
          type: array
          title: Results
      type: object
      required:
      - results
      title: MappingResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
